Hw04 auth
Sergey-Markov/nodejs-homework-rest-api pull request #3
Opened 2021-11-17 19:49 UTC by Sergey-Markov

# Домашнее задание 4

-[x]- Создайте ветку `hw04-auth` из ветки `master`.

-[x]- Продолжите создание REST API для работы с коллекцией контактов. Добавьте логику аутентификации/авторизации пользователя с помощью [JWT](https://jwt.io/).

-[x]- В коде создайте схему и модель пользователя для коллекции `users`.

### Регистрация

-[x]- Создайте эндпоинт [`/users/signup`](#registration-request)

-[x]- Сделать валидацию всех обязательных полей (`email` и `password`). При ошибке валидации вернуть [Ошибку валидации] (#registration-validation-error).

-[x]- В случае успешной валидации в модели `User` создать пользователя по данным которые прошли валидацию. Для засолки паролей используй [bcrypt](https://www.npmjs.com/package/bcrypt) или [bcryptjs](https://www.npmjs.com/package/bcryptjs)

-[x]- Если почта уже используется кем-то другим, вернуть [Ошибку Conflict](#registration-conflict-error). -[x]- В противном случае вернуть [Успешный ответ](#registration-success-response).

-[x]- Registration request

-[x]- Registration validation error

-[x]- Registration conflict error

-[x]- Registration success response

```shell
Status: 201 Created
Content-Type: application/json
ResponseBody: {
  "user": {
    "email": "example@example.com",
    "subscription": "starter"
  }
}
```

### Логин

-[x]- Создайте эндпоинт [`/users/login`](#login-request) -[x]- В модели `User` найти пользователя по `email`. -[x]- Сделать валидацию всех обязательных полей (`email` и `password`). При ошибке валидации вернуть [Ошибку валидации](#validation-error-login). -[x]- В противном случае, сравнить пароль для найденного юзера, если пароли совпадают создать токен, сохранить в текущем юзере и вернуть [Успешный ответ](#login-success-response). -[x]- Если пароль или email неверный, вернуть [Ошибку Unauthorized](#login-auth-error). -[x]- Login request -[x]- Login validation error -[x]- Login success response

```shell
Status: 200 OK
Content-Type: application/json
ResponseBody: {
  "token": "exampletoken",
  "user": {
    "email": "example@example.com",
    "subscription": "starter"
  }
}
```

-[x]- Login auth error

### Проверка токена

-[x]- Создайте мидлвар для проверки токена и добавь его ко всем маршрутам, которые должны быть защищены.

- Мидлвар берет токен из заголовков `Authorization`, проверяет токен на валидность.
- В случае ошибки вернуть [Ошибку Unauthorized](#middleware-unauthorized-error).
- Если валидация прошла успешно, получить из токена `id` пользователя. Найти пользователя в базе данных по этому id.
- Если пользователь существует и токен совпадает с тем, что находится в базе, записать его данные в `req.user` и вызвать метод`next()`.
- Если пользователя с таким `id` не существует или токены не совпадают, вернуть [Ошибку Unauthorized](#middleware-unauthorized-error)

### Логаут

-[x]- Создайте ендпоинт [`/users/logout`](#logout-request) -[x]- Добавьте в маршрут мидлвар проверки токена. -[x]- В модели `User` найти пользователя по `_id`. -[x]- Если пользователя не существует вернуть [Ошибку Unauthorized](#logout-unauthorized-error). -[x]- В противном случае, удалить токен в текущем юзере и вернуть [Успешный ответ](#logout-success-response).

### Текущий пользователь - получить данные юзера по токену

-[x]- Создайте эндпоинт [`/users/current`](#current-user-request)

-[x]- Добавьте в маршрут мидлвар проверки токена.

-[x]- Если пользователя не существует вернуть [Ошибку Unauthorized](#current-user-unauthorized-error) -[x]- В противном случае вернуть [Успешный ответ](#current-user-success-response)

#### Current user success response

```shell
Status: 200 OK
Content-Type: application/json
ResponseBody: {
  "email": "example@example.com",
  "subscription": "starter"
}
```

## Дополнительное задание - необязательное

-[x]- Сделать пагинацию с [mongoose-paginate-v2](https://www.npmjs.com/package/mongoose-paginate-v2) для коллекции контактов (GET /contacts?page=1&limit=20).

-[x]- Сделать фильтрацию контактов по полю избранного (GET /contacts?favorite=true)

-[x]- Обновление подписки (`subscription`) пользователя через эндпоинт `PATCH` `/users`. Подписка должна иметь одно из следующих значений `['starter', 'pro', 'business']`

2021-11-21 21:26 UTC, KirillKulakow commented on .env
> -DB_HOST=mongodb+srv://Sergey:wcLQRXDFO2T9kS5A@firstapp.zgm8u.mongodb.net/db-contacts?retryWrites=true&w=majority
файл удалить из репозитория и добавить в .gitignore

2021-11-21 21:28 UTC, KirillKulakow commented on controllers/auth/subscriptionChange.js
> +  console.log(req.body);
удалить

2021-11-21 21:28 UTC, KirillKulakow commented on controllers/auth/subscriptionChange.js
> +  if (password !== ADMIN_PASSWORD) {
это что?

2021-11-21 21:28 UTC, KirillKulakow commented on controllers/auth/subscriptionChange.js
> +  const { id, password, newValue } = req.body;
почему newValue?

2021-11-21 21:29 UTC, KirillKulakow commented on controllers/auth/subscriptionChange.js
> +  console.log(newUserSubscription);
удалить

2021-11-21 21:30 UTC, Sergey-Markov commented on controllers/auth/subscriptionChange.js
> +  if (password !== ADMIN_PASSWORD) {
я подумал что если нужно изменить подписку то это делает админ, сделал проверку на пароль админа

2021-11-21 21:31 UTC, Sergey-Markov commented on controllers/auth/subscriptionChange.js
> +  console.log(req.body);
Удалить всю функцию? Это доп задание

2021-11-21 21:32 UTC, Sergey-Markov commented on .env
> -DB_HOST=mongodb+srv://Sergey:wcLQRXDFO2T9kS5A@firstapp.zgm8u.mongodb.net/db-contacts?retryWrites=true&w=majority
Если я его удалю вы не сможете запустить у себя материалы... Удалять?

2021-11-21 21:33 UTC, Sergey-Markov commented on controllers/auth/subscriptionChange.js
> +  const { id, password, newValue } = req.body;
новое значение подписки

2021-11-21 21:35 UTC, KirillKulakow commented on controllers/contacts/getContactsList.js
> +  const { page, limit, favorite } = req.query;
- было бы хорошо поставить для всех этих параметров дефолтные значения
- можно создать переменную filter и если есть favorite добавлять
- на параметры page и limit сделать проверку на число, если не число - вернуть ошибку badRequest

2021-11-21 21:35 UTC, KirillKulakow commented on controllers/contacts/patchStatusOfContact.js
> +  console.log(favorite);
удалить

2021-11-21 21:37 UTC, KirillKulakow commented on middlewares/authenticate.js
> +    const [bearer, token] = req.headers.authorization.split(" ");
если я буду делать запрос без авторизации на список контактов - приложение сломается

2021-11-21 21:38 UTC, KirillKulakow requested changes
Need fix

2021-11-22 08:33 UTC, Sergey-Markov commented on .env
> -DB_HOST=mongodb+srv://Sergey:wcLQRXDFO2T9kS5A@firstapp.zgm8u.mongodb.net/db-contacts?retryWrites=true&w=majority
удалил указанный файл на удаленном репозитории

2021-11-22 08:46 UTC, Sergey-Markov commented on controllers/auth/subscriptionChange.js
> +  console.log(req.body);
удалил консоли

2021-11-22 08:56 UTC, Sergey-Markov commented on controllers/auth/subscriptionChange.js
> +  const { id, password, newValue } = req.body;
change name variable on newValueOfSubscription

2021-11-22 08:56 UTC, Sergey-Markov commented on controllers/auth/subscriptionChange.js
> +  console.log(newUserSubscription);
удалил консоль.лог

2021-11-22 10:04 UTC, Sergey-Markov commented on controllers/contacts/getContactsList.js
> +  const { page, limit, favorite } = req.query;
1. Для favorite есть дефолтное значение при создании контакта  - false
2. выполнено - на параметры page и limit сделать проверку на число, если не число - вернуть ошибку badRequest

2021-11-22 10:06 UTC, Sergey-Markov commented on controllers/contacts/patchStatusOfContact.js
> +  console.log(favorite);
deleted

2021-11-22 10:43 UTC, Sergey-Markov commented on middlewares/authenticate.js
> +    const [bearer, token] = req.headers.authorization.split(" ");
добавил проверку на наличие хедера авторизации и соответственно добавил вместо ошибки респонс с месседжером об ошибке авторизации

2021-11-22 19:38 UTC, KirillKulakow commented on .env
> -DB_HOST=mongodb+srv://Sergey:wcLQRXDFO2T9kS5A@firstapp.zgm8u.mongodb.net/db-contacts?retryWrites=true&w=majority
для проверки я просто вставлю доступ к своей базе)) не переживай

2021-11-22 19:41 UTC, KirillKulakow commented on controllers/auth/subscriptionChange.js
> +  if (password !== ADMIN_PASSWORD) {
делать проверку по паролю админа - это очень плохой вариант
заморочиться можно но зачем делать лишнее)
Можно сделать отдельное поле в схеме юзера - например с названием role и на выбор там будет или user или admin
и соответственно по этому полю у юзера уже делать определенный функционал

2021-11-22 19:59 UTC, KirillKulakow commented on controllers/contacts/getContactsList.js
> +  if (page >= 1 && limit >= 1) {
интересная проверка

2021-11-22 20:02 UTC, KirillKulakow approved these changes

2021-11-23 07:09 UTC, merged