Hw05 avatars
Sergey-Markov/nodejs-homework-rest-api pull request #4
Opened 2021-11-26 13:11 UTC by Sergey-Markov

# Домашнее задание 5

Создай ветку `hw05-avatars` из ветки `master`.

Продолжи создание REST API для работы с коллекцией контактов. Добавь возможность загрузки аватарки пользователя через [Multer](https://github.com/expressjs/multer).

- [x] ## Шаг 1

Создай папку `public` для раздачи статики. В этой папке сделай папку `avatars`. Настрой Express на раздачу статических файлов из папки `public`.

Положи любое изображение в папку `public/avatars` и проверь что раздача статики работает. При переходе по такому URL браузер отобразит изображение.

```shell
http://localhost:<порт>/avatars/<имя файла с расширением>
```

- [x] ## Шаг 2

В схему пользователя добавь новое свойство `avatarURL` для хранения изображения.

```shell
{
  ...
  avatarURL: String,
  ...
}
```

- Используй пакет [gravatar](https://www.npmjs.com/package/gravatar) для того чтобы при регистрации нового пользователя сразу сгенерить ему аватар по его `email`.

## Шаг 3

При регистрации пользователя:

- Создавай ссылку на аватарку пользователя с помощью [gravatar](https://www.npmjs.com/package/gravatar)
- Полученный URL сохрани в поле `avatarURL` во время создания пользователя

- [ ] ## Шаг 4

Добавь возможность обновления аватарки, создав эндпоинт `/users/avatars` и используя метод `PATCH`.

![avatar upload from postman](./avatar-upload.png)

```shell
# Запрос
PATCH /users/avatars
Content-Type: multipart/form-data
Authorization: "Bearer {{token}}"
RequestBody: загруженный файл
# Успешный ответ
Status: 200 OK
Content-Type: application/json
ResponseBody: {
  "avatarURL": "тут будет ссылка на изображение"
}
# Неуспешный ответ
Status: 401 Unauthorized
Content-Type: application/json
ResponseBody: {
  "message": "Not authorized"
}
```

- Создай папку tmp в корне проекта и сохраняй в неё загруженную аватарку.
- Обработай аватарку пакетом [jimp](https://www.npmjs.com/package/jimp) и задай для нее размеры 250 на 250
- Перенеси аватарку пользователя из папки tmp в папку `public/avatars` и дай ей уникальное имя для конкретного пользователя.
- Полученный `URL` `/avatars/<имя файла с расширением>` сохрани в поле `avatarURL` пользователя

2021-11-26 20:09 UTC, KirillKulakow commented on controllers/auth/changeUserAvatar.js
> +  // проверка на коректного юзера для изменения картинки только тем юзером кому пренадлежит акаунт
не пойму - зачем здесь тебе проверка, если у тебя авторизация проверяется ранее в миддлваре аутентификации

2021-11-26 20:09 UTC, KirillKulakow commented on controllers/auth/changeUserAvatar.js
> +  }
до сюда

2021-11-26 20:10 UTC, KirillKulakow commented on controllers/auth/registration.js
> +// const ddd = require("../../public/avatars/avatarkaQttR.jpg");
удалить

2021-11-26 20:11 UTC, KirillKulakow commented on controllers/auth/registration.js
> +const defAvatarPath = path.join(
удалить

2021-11-26 20:11 UTC, KirillKulakow commented on controllers/auth/registration.js
> +  const avatarURL = gravatar.url(defAvatarPath);
вместо жалобной строки ниже можно просто добавить опцию протокола

2021-11-26 20:12 UTC, KirillKulakow requested changes
Need fix

2021-11-26 20:37 UTC, Sergey-Markov commented on controllers/auth/changeUserAvatar.js
> +  // проверка на коректного юзера для изменения картинки только тем юзером кому пренадлежит акаунт
для того чтоб мог только юзер которому пренадлежит акаунт юзера у которого хотят поменять картинку это сделать, а не все кто залогинены

2021-11-26 20:39 UTC, Sergey-Markov commented on controllers/auth/changeUserAvatar.js
> +  }
проверку на емайл и пароль требовали в предыдущих работах

2021-11-26 21:12 UTC, Sergey-Markov commented on controllers/auth/registration.js
> +// const ddd = require("../../public/avatars/avatarkaQttR.jpg");
удалил

2021-11-26 21:12 UTC, Sergey-Markov commented on controllers/auth/registration.js
> +const defAvatarPath = path.join(
удалил

2021-11-26 21:14 UTC, Sergey-Markov commented on controllers/auth/registration.js
> +  const avatarURL = gravatar.url(defAvatarPath);
**_**вместо жалобной строки ниже ----- просто добавил опцию протокола ;)**_**

2021-11-27 08:05 UTC, Sergey-Markov commented on controllers/auth/changeUserAvatar.js
> +  }
удалил

2021-11-27 08:05 UTC, Sergey-Markov commented on controllers/auth/changeUserAvatar.js
> +  // проверка на коректного юзера для изменения картинки только тем юзером кому пренадлежит акаунт
понял ошибку и удалил свою логику к чертям

2021-11-27 17:34 UTC, KirillKulakow commented on controllers/auth/registration.js
> +  const avatarURL = gravatar.url(defAvatarPath);
сори, что-то пошло не так))

2021-11-27 17:41 UTC, KirillKulakow commented on controllers/auth/registration.js
> +  const avatarURL = gravatar.url("emerleite@gmail.com", { protocol: "https" });
почему именно emerleite@gmail.com?

2021-11-27 17:41 UTC, KirillKulakow approved these changes

2021-11-27 17:53 UTC, Sergey-Markov commented on controllers/auth/registration.js
> +  const avatarURL = gravatar.url("emerleite@gmail.com", { protocol: "https" });
дефолтный вариант

2021-11-27 17:54 UTC, merged